apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
spec:
  type: NodePort
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
      nodePort: 30006