apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'dotnet_app'
        metrics_path: /metrics
        static_configs:
          - targets: ['172.23.86.154:30006']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']