apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
    nodePort: 30072  # Adicione esta linha
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30172  # Adicione esta linha
  type: NodePort  # Altere de LoadBalancer para NodePort